version: 1
disable_existing_loggers: true

formatters:
  standard:
    format: '%(asctime)s: %(levelname)s in %(funcName)s, logger %(name)s: %(message)s'
    datefmt: '%Y-%m-%d %I:%M:%S'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stderr

loggers:
  trends:
    level: DEBUG
    handlers: [console]

